version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    ports:
      - 3307:3306
    volumes:
    - ./db2:/var/lib/mysql
  app:
    image: oauth2
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&maxReconnects=1500
    depends_on:
      - docker-mysql